// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZIA3B1dmDGqIRDm3JiTkWI530MYapYM',
    appId: '1:370765198398:web:8e254178da911ef41a8d6f',
    messagingSenderId: '370765198398',
    projectId: 'tram-doc-519fe',
    authDomain: 'tram-doc-519fe.firebaseapp.com',
    storageBucket: 'tram-doc-519fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjZIA3B1dmDGqIRDm3JiTkWI530MYapYM',
    appId: '1:370765198398:android:bde734138deab5091a8d6f',
    messagingSenderId: '370765198398',
    projectId: 'tram-doc-519fe',
    storageBucket: 'tram-doc-519fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZIA3B1dmDGqIRDm3JiTkWI530MYapYM',
    appId: '1:370765198398:ios:YOUR_APP_ID',
    messagingSenderId: '370765198398',
    projectId: 'tram-doc-519fe',
    storageBucket: 'tram-doc-519fe.firebasestorage.app',
    iosBundleId: 'com.tramdoc.tramDoc',
  );
}
